### ISSUE TITLE
Annotations are showing for both sides

### ISSUE THREAD

**Issue by morrtz** [jboecker/dcs-mission-planner#23]
When doing annotation with the blue credentials, the red side can see the annotations that are created.

**Comment by morrtz** [comment]
Checked now, Also routes for both sides are showing.

**Comment by jboecker** [comment]
There was a server-side and a client-side cause for this bug (both fixed now).

When a new object was added, the server would use the coalition that sent the new object to filter transaction info instead of the coalition of the receiver, which caused the new information to be sent to anyone. This was also the reason why routes were showing up.

The client-side cause was that the client simply did not set the visiblity attribute on newly created annotations.

Both issues are now fixed in the master branch and the fixes will be released as part of v0.0.1-beta9 shortly.
