### ISSUE TITLE
Add spectator links for blue and red side

### ISSUE THREAD

**Issue by morrtz** [jboecker/dcs-mission-planner#25]
The planner by itself is an excellent tool.
But when we plan mission, only the one who planned the routes can actually see them and if you publish the link to see your side planning whoever joins can change things by mistake and without intent.

If there are links for spectators for each side it will be easier to show the routes in a briefing to users we don't want to be able to change things, only allow the capability of showing active route and that's it.

**Comment by jboecker** [comment]
I have pushed a new server version to master that generates spectator URLs.
(Be sure to run "python serve.py upgrade" once to generate spectator passwords for old instances, otherwise they will stop working.)
In the client repository, there is an updated admin tool on the master branch that displays them.

When logged in with a spectator URL, the UI does not change but the server will reject every edit attempt.
